# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-25 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WxHead',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=20, verbose_name='微信昵称')),
                ('phonoe', models.CharField(max_length=20, verbose_name='手机型号')),
                ('head_image', models.ImageField(upload_to='', verbose_name='头像')),
            ],
            options={
                'verbose_name': '微信用户信息',
                'verbose_name_plural': '微信用户信息',
                'db_table': 'db_others',
            },
        ),
    ]
