# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-29 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='单价')),
                ('descr', models.CharField(max_length=24, verbose_name='描述')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'tb_item',
            },
        ),
    ]
