# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-16 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20181216_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='item',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新日期'),
        ),
    ]
